### ISSUE TITLE
From/To in tx details page

### ISSUE THREAD

**Issue by saimeunt** [walnuthq/op-scan#14]
# From/To in tx details page

## ⚠️ Reading contributors guidelines to get assigned is MANDATORY!

[Read contributors guidelines](https://github.com/walnuthq/op-scan/issues/1)

## User stories

- As a user, I want to see the from and to addresses of the transaction in the tx details page.
From / To addresses should be links to the corresponding account details page.
- I want to be able to differentiate between EOA to EOA transfers and EOA to contract interaction.

## Validation

You should study how Etherscan displays these fields based on the different possible scenarios: https://optimistic.etherscan.io/tx/0x3b680d4727227d6afb35ddf620c3b16e33877f3cc06ec1151a6c45bd167b9f30

![Image](https://github.com/walnuthq/op-scan/assets/5597359/bf3fe6d9-81ec-4cff-9199-f2754b263ec3)

In particular, we need to detect contract interaction and if execution went through or reverted.

## Implementation

Use the data available in the transaction object in the tx details page to display the correct information.
You should continue the work already done on the basic tx detail page and reuse the description list component.

**Comment by Ayoazeez26** [comment]
I would love to work on this, [here is my OD profile](https://app.onlydust.com/u/Ayoazeez26)

**Comment by melnikga** [comment]
Hi, can I take this

**Comment by Ugo-X** [comment]
Hello Project Lead! I'm Ugo, a fullstack(js,React,Node,Next.js,Three.js) developer with a strong track record in OD hack projects. I've been actively involved since Edition 2, contributing to various initiatives, and I'm thrilled to be part of Edition 5!
Having used OnlyDust extensively (see my profile:https://app.onlydust.com/u/Ugo-X)), I'm confident in my ability to tackle new challenges within this edition.
I'm eager to leverage my skills and experience to contribute effectively.

# Here's how I plan to approach the issue:
* I would build out the to/from transactions page making sure to sort it in order of latest transactions
* Then I would integrate a sorting sequence so the user can sort between EOA to EOA transfers and EOA to contract transactions
* I would test this logic to make sure it works perfectly without any errors or breaks

**Comment by PoulavBhowmick03** [comment]
Hello Project lead and maintainers, I am Poulav, a fullstack web3 developer. I have good grasp in MERN stack, Next.js, Typescript and other currently leading tech stacks in web. This is my first time contributing in this project but I feel I can work on this in great ease. 
Here is my Profile:- https://app.onlydust.com/u/PoulavBhowmick03
Not much, since recently opened the account, but I can get this done since I have worked on similar issues before
# How I plan to do this
> I will build a similar looking div in the tx/[hash] route showing To: and From: 
> I will then import the Transaction from the lib/types.ts and pass it as props to the main function and then use it to display the respective transaction from and to address in the page.

I believe if I am assigned this, I can get it done in the quickest time.
Regards
Thank you!

**Comment by kamuik16** [comment]
I'm up for it!
[OD Hack Profile](https://app.onlydust.com/u/kamuik16)

**Comment by jedstroke** [comment]
Hello Walnut Fam,

I am a seasoned fullstack developer with a focus on front-end development. Although I haven't contributed to Walnut before, I am excited by your welcoming stance: "However, if you are new, don’t worry—we are eager to attract new talent..."

I am passionate about creating responsive, modular, and scalable UI components and would love to take on this issue.

Here are my profiles for your reference:

- OnlyDust: [Jedstroke's Profile](https://app.onlydust.com/u/jedstroke)
- Portfolio: [Jedidiah Gabriel](https://www.jedshock.com/)
Looking forward to contributing!

Best regards,
Jedidiah Gabriel

**Comment by diegoTech14** [comment]
Hello, @saimeunt 

My name is Diego Duarte, I'm a JS full-stack developer, this is my first ODHack and my first time contributing to Walnut. I would like to help with this issue.

Here is my proposal:
1. Build a component similar to the example.
2. I will use the Transaction from the lib/types.ts to display the necessary transaction information on the page.

- OnlyDust: https://app.onlydust.com/u/diegoTech14

Thank you for your consideration.

**Comment by saimeunt** [comment]
@PoulavBhowmick03 provided a clear comment showing a good understanding of what needs to be done, assigning to you.

@kamuik16 I appreciate your contribution however we have a strict policy regarding issue assignment and we can't accept PRs on issues not assigned beforehand. There will be more issues in the coming days, feel free to comment on them to receive assignment.
