### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by celochoi** [walnuthq/op-scan#72]
When performing pnpm build on the current main branch, the following error occurs.
```
./src/hooks/useSearch.ts
Error:
  x Expected '>', got 'ref'
```

It seems to have started occurring after [this commit](https://github.com/walnuthq/op-scan/commit/a440c9763b41bb9ec084ed22c81fb7c0cff99331).
Could you check it?

**Comment by saimeunt** [comment]
@celochoi You are right, it should be fixed by the latest commit now, thank you for pointing this out!
I'm curious what's your use case for trying out op-scan, would you be open to share it with us?
We're trying to reach essential/basic features parity with Etherscan/Blockscout and then we'll dive into op-stack related features (SuperchainERC20, ERC-7683) but most importantly we want to bring features that potential users are interested in!

**Comment by ScottyDavies** [comment]
@celochoi I am open to work on this

**Comment by 0xdevcollins** [comment]
Can I work on this please @celochoi , please I’d love to be given the opportunity to contribute here.

**Comment by celochoi** [comment]
@saimeunt  I apologize for the delayed response. I'm interested in setting up an OP Stack L2 chain, and I anticipate that implementing my own scanner would require substantial resources. Given that many chains using the OP Stack exist, I expected there would be open-source scanners available, and I have come across Op Scan during search. :)

**Comment by celochoi** [comment]
Since a scanner is essential for chain operation, I'm paying close attention to it. Thank you.

**Comment by celochoi** [comment]
It appears that this issue has been resolved in the latest main branch, so I will go ahead and close it.
